---
name: Build and release container

on:
  push:
    branches:
      - "master"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */24 * * *' # Every 24 hours

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: install node dependencies
        run: npm run ci

      - name: Update swagger.json file
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/invidious/docs.invidious.io:latest
